services:
  shortener:
    image: ghcr.io/mrrizaldi/shortener:latest
    container_name: shortener_app
    restart: always
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env

# No need for volumes or networks since we're using host network or external PostgreSQL
